require: rubocop

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - Guardfile
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: [
    'describe',
    'xdescribe',
    'context',
    'xcontext',
    'it',
    'xit',
    'let',
    'before',
    'after',
    'aggregate_failures'
  ]

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'spec/***/**/*'
    - 'spec/****/***/**/*'
    - 'spec/*****/****/***/*'
